server {
    # Run on port 8080 (Common constraint for Google Cloud Run containerized Apps)
    listen 8080;
    
    server_name localhost;

    # ── 1. Serve frontend SPA ────────────────────────────────────────────────
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        
        # This handles React Router's client side routing: if file isn't found, fallback to index.html
        try_files $uri $uri/ /index.html;
    }

}
