steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${SHORT_SHA}

images:
  - ${_AR_HOST}/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${SHORT_SHA}

substitutions:
  _AR_HOST: asia-southeast1-docker.pkg.dev
  _AR_REPO: legal-chatbot
  _IMAGE_NAME: orchestrator
